server:
  port: 8080
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://host.docker.internal:3306/loan?characterEncoding=UTF-8&serverTimeZone=Asia/Seoul
#    url: jdbc:mysql://localhost:3306/loan?characterEncoding=UTF-8&serverTimeZone=Asia/Seoul
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      location: C:\jieun\fastcampus\9\file


logging.level:
  org.hibernate.SQL: debug
